// protos/issuer.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: protos/issuer.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgRequestVC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Vp  string `protobuf:"bytes,2,opt,name=vp,proto3" json:"vp,omitempty"`
}

func (x *MsgRequestVC) Reset() {
	*x = MsgRequestVC{}
	mi := &file_protos_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRequestVC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRequestVC) ProtoMessage() {}

func (x *MsgRequestVC) ProtoReflect() protoreflect.Message {
	mi := &file_protos_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRequestVC.ProtoReflect.Descriptor instead.
func (*MsgRequestVC) Descriptor() ([]byte, []int) {
	return file_protos_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *MsgRequestVC) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *MsgRequestVC) GetVp() string {
	if x != nil {
		return x.Vp
	}
	return ""
}

type MsgResponseVC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Vc     string `protobuf:"bytes,3,opt,name=vc,proto3" json:"vc,omitempty"`
}

func (x *MsgResponseVC) Reset() {
	*x = MsgResponseVC{}
	mi := &file_protos_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResponseVC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResponseVC) ProtoMessage() {}

func (x *MsgResponseVC) ProtoReflect() protoreflect.Message {
	mi := &file_protos_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResponseVC.ProtoReflect.Descriptor instead.
func (*MsgResponseVC) Descriptor() ([]byte, []int) {
	return file_protos_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *MsgResponseVC) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *MsgResponseVC) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgResponseVC) GetVc() string {
	if x != nil {
		return x.Vc
	}
	return ""
}

type MsgRequestIDVC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did       string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile    string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	BirthDate string `protobuf:"bytes,4,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Gender    string `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *MsgRequestIDVC) Reset() {
	*x = MsgRequestIDVC{}
	mi := &file_protos_issuer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRequestIDVC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRequestIDVC) ProtoMessage() {}

func (x *MsgRequestIDVC) ProtoReflect() protoreflect.Message {
	mi := &file_protos_issuer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRequestIDVC.ProtoReflect.Descriptor instead.
func (*MsgRequestIDVC) Descriptor() ([]byte, []int) {
	return file_protos_issuer_proto_rawDescGZIP(), []int{2}
}

func (x *MsgRequestIDVC) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *MsgRequestIDVC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgRequestIDVC) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *MsgRequestIDVC) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *MsgRequestIDVC) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

var File_protos_issuer_proto protoreflect.FileDescriptor

var file_protos_issuer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x22, 0x30, 0x0a,
	0x0c, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x43, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x76, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x70, 0x22,
	0x49, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x43,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x63, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x56, 0x43, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x32, 0x8c, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0d, 0x49, 0x73, 0x73, 0x75, 0x65, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x56, 0x43, 0x12, 0x14, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x43, 0x1a, 0x15, 0x2e, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x43,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x49, 0x73, 0x73, 0x75, 0x65, 0x49, 0x44, 0x56, 0x43, 0x12,
	0x16, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x56, 0x43, 0x1a, 0x15, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72,
	0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x43, 0x22, 0x00,
	0x42, 0x11, 0x5a, 0x0f, 0x73, 0x73, 0x69, 0x2d, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_issuer_proto_rawDescOnce sync.Once
	file_protos_issuer_proto_rawDescData = file_protos_issuer_proto_rawDesc
)

func file_protos_issuer_proto_rawDescGZIP() []byte {
	file_protos_issuer_proto_rawDescOnce.Do(func() {
		file_protos_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_issuer_proto_rawDescData)
	})
	return file_protos_issuer_proto_rawDescData
}

var file_protos_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_issuer_proto_goTypes = []any{
	(*MsgRequestVC)(nil),   // 0: issuer.MsgRequestVC
	(*MsgResponseVC)(nil),  // 1: issuer.MsgResponseVC
	(*MsgRequestIDVC)(nil), // 2: issuer.MsgRequestIDVC
}
var file_protos_issuer_proto_depIdxs = []int32{
	0, // 0: issuer.SimpleIssuer.IssueSimpleVC:input_type -> issuer.MsgRequestVC
	2, // 1: issuer.SimpleIssuer.IssueIDVC:input_type -> issuer.MsgRequestIDVC
	1, // 2: issuer.SimpleIssuer.IssueSimpleVC:output_type -> issuer.MsgResponseVC
	1, // 3: issuer.SimpleIssuer.IssueIDVC:output_type -> issuer.MsgResponseVC
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_issuer_proto_init() }
func file_protos_issuer_proto_init() {
	if File_protos_issuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_issuer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_issuer_proto_goTypes,
		DependencyIndexes: file_protos_issuer_proto_depIdxs,
		MessageInfos:      file_protos_issuer_proto_msgTypes,
	}.Build()
	File_protos_issuer_proto = out.File
	file_protos_issuer_proto_rawDesc = nil
	file_protos_issuer_proto_goTypes = nil
	file_protos_issuer_proto_depIdxs = nil
}
